result: ERROR
cause: "ERROR[cause=MobileHarnessException: Test failed to allocate devices.]"
